name: Go

on:
  push:
    branches: [ "main", "v0.1" ]
  pull_request:
    branches: [ "main", "v0.1" ]

jobs:
  runner-job:
    strategy:
      matrix:
        go: [1.21.0]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: "root"
          POSTGRES_DB: "test"

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go}}
        env:
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DATABASE_NAME: test
          DATABASE_USER: root
          DATABASE_PASSWORD: postgres
          CONFIG_PATH: config/config.yaml
      - name: Build
        run: go build -v cmd/cloud/*.go

      - name: Test
        run: go test -v ./...